2023-04-24 15:14:43,448: [3447] m.main:INFO: Registered plugins: DetectUninitializedMemory, DetectDelegatecall, DetectExternalCallAndLeak, DetectInvalid, DetectIntegerOverflow, DetectUnusedRetVal, DetectReentrancySimple, DetectReentrancyAdvanced, DetectEnvInstruction, DetectSuicidal, DetectUninitializedStorage
2023-04-24 15:14:43,449: [3447] m.main:INFO: Beginning analysis
2023-04-24 15:14:43,457: [3447] m.e.manticore:INFO: Starting symbolic create contract
2023-04-24 15:14:44,743: [3447] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-04-24 15:26:59,800: [3755] m.c.worker:ERROR: Exception in state 1: EthereumError('Conditional not concretized at JMPDEST check')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/worker.py", line 119, in run
    current_state.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2680, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1205, in execute
    self._check_jmpdest()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1142, in _check_jmpdest
    raise EthereumError("Conditional not concretized at JMPDEST check")
manticore.exceptions.EthereumError: Conditional not concretized at JMPDEST check
 
2023-04-24 15:27:00,042: [3447] m.e.manticore:INFO: 4 alive states, 10 terminated states
2023-04-24 15:27:01,218: [3447] m.e.manticore:INFO: Starting symbolic transaction: 1
2023-04-24 15:37:01,343: [7985] m.c.worker:ERROR: Exception in state 8: SolverError('')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/worker.py", line 119, in run
    current_state.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2680, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1212, in execute
    self._advance(result)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1163, in _advance
    self._publish("did_evm_execute_instruction", last_instruction, last_arguments, result)
  File "/usr/local/lib/python3.9/dist-packages/manticore/utils/event.py", line 128, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/utils/event.py", line 145, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/utils/event.py", line 145, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/utils/event.py", line 143, in _publish_impl
    sink._publish_impl(_name, self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/utils/event.py", line 136, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/detectors.py", line 534, in did_evm_execute_instruction_callback
    if state.can_be_true(iou):
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 298, in can_be_true
    return self._solver.can_be_true(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 402, in can_be_true
    return self._is_sat()
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2023-04-24 15:39:18,689: [7987] m.c.worker:ERROR: Exception in state 9: SolverError('')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/worker.py", line 119, in run
    current_state.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2680, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1205, in execute
    self._check_jmpdest()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1138, in _check_jmpdest
    should_check_jumpdest_solutions = Z3Solver().get_all_values(
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2023-04-24 15:39:26,170: [7973] m.c.worker:ERROR: Exception in state 4: SolverError('')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/worker.py", line 119, in run
    current_state.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2680, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1205, in execute
    self._check_jmpdest()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1138, in _check_jmpdest
    should_check_jumpdest_solutions = Z3Solver().get_all_values(
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2023-04-24 15:39:26,590: [7971] m.c.worker:ERROR: Exception in state 3: SolverError('')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/worker.py", line 119, in run
    current_state.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2680, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1205, in execute
    self._check_jmpdest()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1138, in _check_jmpdest
    should_check_jumpdest_solutions = Z3Solver().get_all_values(
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2023-04-24 15:40:39,809: [7969] m.c.worker:ERROR: Exception in state 2: EthereumError('Conditional not concretized at JMPDEST check')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/worker.py", line 119, in run
    current_state.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2680, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1205, in execute
    self._check_jmpdest()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1142, in _check_jmpdest
    raise EthereumError("Conditional not concretized at JMPDEST check")
manticore.exceptions.EthereumError: Conditional not concretized at JMPDEST check
 
2023-04-24 15:40:57,656: [7968] m.c.worker:ERROR: Exception in state 1: EthereumError('Conditional not concretized at JMPDEST check')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/worker.py", line 119, in run
    current_state.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2680, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1205, in execute
    self._check_jmpdest()
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 1142, in _check_jmpdest
    raise EthereumError("Conditional not concretized at JMPDEST check")
manticore.exceptions.EthereumError: Conditional not concretized at JMPDEST check
 
2023-04-24 15:40:57,811: [3447] m.e.manticore:INFO: 15 alive states, 47 terminated states
2023-04-24 15:41:00,054: [15349] m.c.manticore:INFO: Generated testcase No. 0 - RETURN(3 txs)
2023-04-24 15:41:00,322: [15351] m.c.manticore:INFO: Generated testcase No. 1 - RETURN(3 txs)
2023-04-24 15:41:00,353: [15353] m.c.manticore:INFO: Generated testcase No. 2 - RETURN(3 txs)
2023-04-24 15:41:00,542: [15348] m.c.manticore:INFO: Generated testcase No. 3 - RETURN(3 txs)
2023-04-24 15:41:00,606: [15363] m.c.manticore:INFO: Generated testcase No. 4 - RETURN(3 txs)
2023-04-24 15:41:00,599: [15360] m.c.manticore:INFO: Generated testcase No. 6 - RETURN(3 txs)
2023-04-24 15:41:00,652: [15365] m.c.manticore:INFO: Generated testcase No. 5 - RETURN(3 txs)
2023-04-24 15:41:00,653: [15357] m.c.manticore:INFO: Generated testcase No. 7 - RETURN(3 txs)
2023-04-24 15:41:00,650: [15359] m.c.manticore:INFO: Generated testcase No. 8 - RETURN(3 txs)
2023-04-24 15:41:00,689: [15354] m.c.manticore:INFO: Generated testcase No. 9 - RETURN(3 txs)
2023-04-24 15:41:19,589: [15365] m.c.manticore:INFO: Generated testcase No. 12 - RETURN(3 txs)
2023-04-24 15:41:19,627: [15363] m.c.manticore:INFO: Generated testcase No. 11 - RETURN(3 txs)
2023-04-24 15:41:19,633: [15359] m.c.manticore:INFO: Generated testcase No. 10 - RETURN(3 txs)
2023-04-24 15:41:20,130: [15349] m.c.manticore:INFO: Generated testcase No. 13 - RETURN(3 txs)
2023-04-24 15:41:20,203: [15348] m.c.manticore:INFO: Generated testcase No. 14 - RETURN(3 txs)
2023-04-24 15:41:20,372: [15354] m.c.manticore:INFO: Generated testcase No. 15 - REVERT(2 txs)
2023-04-24 15:41:20,598: [15357] m.c.manticore:INFO: Generated testcase No. 16 - RETURN(1 txs)
2023-04-24 15:41:20,986: [15351] m.c.manticore:INFO: Generated testcase No. 17 - REVERT(2 txs)
2023-04-24 15:41:21,624: [15360] m.c.manticore:INFO: Generated testcase No. 18 - REVERT(2 txs)
2023-04-24 15:41:21,759: [15353] m.c.manticore:INFO: Generated testcase No. 19 - REVERT(2 txs)
2023-04-24 15:41:28,224: [15357] m.c.manticore:INFO: Generated testcase No. 20 - REVERT(2 txs)
2023-04-24 15:41:30,344: [15351] m.c.manticore:INFO: Generated testcase No. 21 - REVERT(2 txs)
2023-04-24 15:41:30,488: [15354] m.c.manticore:INFO: Generated testcase No. 22 - REVERT(2 txs)
2023-04-24 15:41:32,355: [15360] m.c.manticore:INFO: Generated testcase No. 23 - REVERT(2 txs)
2023-04-24 15:41:32,581: [15353] m.c.manticore:INFO: Generated testcase No. 24 - REVERT(2 txs)
2023-04-24 15:41:37,703: [15363] m.c.manticore:INFO: Generated testcase No. 25 - RETURN(2 txs)
2023-04-24 15:41:38,025: [15349] m.c.manticore:INFO: Generated testcase No. 26 - RETURN(2 txs)
2023-04-24 15:41:38,173: [15359] m.c.manticore:INFO: Generated testcase No. 27 - RETURN(2 txs)
2023-04-24 15:41:38,223: [15348] m.c.manticore:INFO: Generated testcase No. 28 - RETURN(2 txs)
2023-04-24 15:41:38,739: [15365] m.c.manticore:INFO: Generated testcase No. 29 - REVERT(3 txs)
2023-04-24 15:41:42,153: [15357] m.c.manticore:INFO: Generated testcase No. 30 - REVERT(3 txs)
2023-04-24 15:41:44,021: [15351] m.c.manticore:INFO: Generated testcase No. 31 - REVERT(3 txs)
2023-04-24 15:41:44,166: [15354] m.c.manticore:INFO: Generated testcase No. 32 - REVERT(3 txs)
2023-04-24 15:41:45,138: [15360] m.c.manticore:INFO: Generated testcase No. 33 - REVERT(3 txs)
2023-04-24 15:41:51,545: [15363] m.c.manticore:INFO: Generated testcase No. 34 - REVERT(3 txs)
2023-04-24 15:41:51,902: [15349] m.c.manticore:INFO: Generated testcase No. 35 - REVERT(3 txs)
2023-04-24 15:41:52,071: [15348] m.c.manticore:INFO: Generated testcase No. 36 - REVERT(3 txs)
2023-04-24 15:41:52,636: [15359] m.c.manticore:INFO: Generated testcase No. 37 - REVERT(3 txs)
2023-04-24 15:41:57,804: [15365] m.c.manticore:INFO: Generated testcase No. 38 - REVERT(3 txs)
2023-04-24 15:41:59,950: [15357] m.c.manticore:INFO: Generated testcase No. 39 - REVERT(3 txs)
2023-04-24 15:42:01,972: [15354] m.c.manticore:INFO: Generated testcase No. 40 - REVERT(3 txs)
2023-04-24 15:42:03,283: [15351] m.c.manticore:INFO: Generated testcase No. 41 - REVERT(3 txs)
2023-04-24 15:42:03,941: [15360] m.c.manticore:INFO: Generated testcase No. 42 - REVERT(3 txs)
2023-04-24 15:42:09,142: [15349] m.c.manticore:INFO: Generated testcase No. 43 - REVERT(3 txs)
2023-04-24 15:42:10,001: [15363] m.c.manticore:INFO: Generated testcase No. 44 - REVERT(3 txs)
2023-04-24 15:42:10,852: [15348] m.c.manticore:INFO: Generated testcase No. 45 - REVERT(3 txs)
2023-04-24 15:42:13,006: [15359] m.c.manticore:INFO: Generated testcase No. 46 - REVERT(3 txs)
2023-04-24 15:42:17,543: [15365] m.c.manticore:INFO: Generated testcase No. 47 - REVERT(3 txs)
2023-04-24 15:42:19,766: [15357] m.c.manticore:INFO: Generated testcase No. 48 - REVERT(3 txs)
2023-04-24 15:42:21,148: [15354] m.c.manticore:INFO: Generated testcase No. 49 - REVERT(3 txs)
2023-04-24 15:42:23,235: [15351] m.c.manticore:INFO: Generated testcase No. 50 - REVERT(3 txs)
2023-04-24 15:42:23,609: [15360] m.c.manticore:INFO: Generated testcase No. 51 - REVERT(3 txs)
2023-04-24 15:42:25,504: [15349] m.c.manticore:INFO: Generated testcase No. 52 - REVERT(3 txs)
2023-04-24 15:42:27,421: [15348] m.c.manticore:INFO: Generated testcase No. 53 - REVERT(3 txs)
2023-04-24 15:42:27,640: [15363] m.c.manticore:INFO: Generated testcase No. 54 - REVERT(3 txs)
2023-04-24 15:42:29,800: [15359] m.c.manticore:INFO: Generated testcase No. 55 - REVERT(3 txs)
2023-04-24 15:42:37,682: [15365] m.c.manticore:INFO: Generated testcase No. 56 - REVERT(3 txs)
2023-04-24 15:42:40,311: [15354] m.c.manticore:INFO: Generated testcase No. 57 - REVERT(3 txs)
2023-04-24 15:42:40,595: [15357] m.c.manticore:INFO: Generated testcase No. 58 - REVERT(3 txs)
2023-04-24 15:42:43,133: [15351] m.c.manticore:INFO: Generated testcase No. 59 - REVERT(3 txs)
2023-04-24 15:42:44,057: [15349] m.c.manticore:INFO: Generated testcase No. 60 - REVERT(3 txs)
2023-04-24 15:42:44,271: [15360] m.c.manticore:INFO: Generated testcase No. 61 - REVERT(3 txs)
2023-04-24 15:42:46,084: [15348] m.c.manticore:INFO: Generated testcase No. 62 - RETURN(1 txs)
2023-04-24 15:42:47,631: [15363] m.c.manticore:INFO: Generated testcase No. 63 - RETURN(2 txs)
2023-04-24 15:42:50,226: [15359] m.c.manticore:INFO: Generated testcase No. 64 - RETURN(2 txs)
2023-04-24 15:42:54,571: [15365] m.c.manticore:INFO: Generated testcase No. 65 - RETURN(2 txs)
2023-04-24 15:42:59,582: [15357] m.c.manticore:INFO: Generated testcase No. 66 - RETURN(2 txs)
2023-04-24 15:42:59,587: [15354] m.c.manticore:INFO: Generated testcase No. 67 - RETURN(2 txs)
2023-04-24 15:43:02,206: [15351] m.c.manticore:INFO: Generated testcase No. 68 - RETURN(2 txs)
Process Process-35:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1627, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1622, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1510, in generate_testcase
    is_something_symbolic = state.platform.dump(stream, state, self, message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2966, in dump
    balance = state.solve_one(balance)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 321, in solve_one
    value = self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 556, in get_value
    if not self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
Process Process-39:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1627, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1622, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1510, in generate_testcase
    is_something_symbolic = state.platform.dump(stream, state, self, message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2966, in dump
    balance = state.solve_one(balance)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 321, in solve_one
    value = self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 556, in get_value
    if not self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
Process Process-38:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1627, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1622, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1510, in generate_testcase
    is_something_symbolic = state.platform.dump(stream, state, self, message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2966, in dump
    balance = state.solve_one(balance)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 321, in solve_one
    value = self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 556, in get_value
    if not self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
Process Process-32:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1627, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1622, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1510, in generate_testcase
    is_something_symbolic = state.platform.dump(stream, state, self, message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2966, in dump
    balance = state.solve_one(balance)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 321, in solve_one
    value = self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 556, in get_value
    if not self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
Process Process-37:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1627, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1622, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1510, in generate_testcase
    is_something_symbolic = state.platform.dump(stream, state, self, message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2966, in dump
    balance = state.solve_one(balance)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 321, in solve_one
    value = self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 556, in get_value
    if not self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
Process Process-41:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1627, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1622, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1510, in generate_testcase
    is_something_symbolic = state.platform.dump(stream, state, self, message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2966, in dump
    balance = state.solve_one(balance)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 321, in solve_one
    value = self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 556, in get_value
    if not self._is_sat():
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
Process Process-36:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1627, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1622, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1510, in generate_testcase
    is_something_symbolic = state.platform.dump(stream, state, self, message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2966, in dump
    balance = state.solve_one(balance)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 321, in solve_one
    value = self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 557, in get_value
    raise SolverError("Model is not available")
manticore.exceptions.SolverError: Model is not available
Process Process-34:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1627, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1622, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/ethereum/manticore.py", line 1510, in generate_testcase
    is_something_symbolic = state.platform.dump(stream, state, self, message)
  File "/usr/local/lib/python3.9/dist-packages/manticore/platforms/evm.py", line 2966, in dump
    balance = state.solve_one(balance)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/state.py", line 321, in solve_one
    value = self._solver.get_value(self._constraints, expr)
  File "/usr/local/lib/python3.9/dist-packages/manticore/core/smtlib/solver.py", line 557, in get_value
    raise SolverError("Model is not available")
manticore.exceptions.SolverError: Model is not available
2023-04-24 15:47:05,823: [3447] m.c.manticore:INFO: Results in /content/mcore_sm49_f_4